<a href="https://colab.research.google.com/github/Yuri-Njathi/PyTorch-Blitz-in-60-minutes/blob/main/Deep_Learning_with_PyTorch_Blitz_60_min_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors

In [1]:
import torch
import numpy as np

In [2]:
data = [[2,5],[6,7]]
t_data = torch.tensor(data)

In [3]:
t_data.shape

torch.Size([2, 2])

In [4]:
!nvidia-smi

Fri Sep 27 03:47:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
torch.cuda.is_available()

True

# from a Numpy array

In [6]:
np_array = np.array(data)

In [7]:
type(np_array)

numpy.ndarray

In [8]:
t_from_array = torch.from_numpy(np_array)

In [9]:
type(t_from_array)

torch.Tensor

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [11]:
# np_array.to(device) #error bound

In [12]:
t_from_array.to(device)

tensor([[2, 5],
        [6, 7]], device='cuda:0')

In [13]:
t_data

tensor([[2, 5],
        [6, 7]])

In [14]:
x_ones = torch.ones_like(t_data)
x_ones #same shape, only ones

tensor([[1, 1],
        [1, 1]])

In [15]:
x_rand = torch.rand_like(t_data, dtype=torch.float)
x_rand

tensor([[0.0369, 0.8399],
        [0.2461, 0.8708]])

In [16]:
x_rand.dtype

torch.float32

In [17]:
t_data.dtype

torch.int64

In [18]:
shape = (2,3) #rows, columns
r_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [19]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones_tensor.to(device)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [21]:
zeros_tensor.shape

torch.Size([2, 3])

In [22]:
zeros_tensor.dtype

torch.float32

In [23]:
zeros_tensor.device

device(type='cpu')

In [24]:
ones_tensor.shape

torch.Size([2, 3])

In [25]:
ones_tensor.dtype

torch.float32

In [26]:
ones_tensor.device

device(type='cpu')

In [27]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
ones_tensor[:,1]=2
ones_tensor

tensor([[1., 2., 1.],
        [1., 2., 1.]])

Joining tensors

In [29]:
t1 = torch.cat([ones_tensor,ones_tensor,ones_tensor],dim=1)

In [30]:
t1

tensor([[1., 2., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 2., 1., 1., 2., 1.]])

In [31]:
t1.shape

torch.Size([2, 9])

In [32]:
#multiplying tensors
'''
syntax
tensor1.mul(tensor2)
tensor1*tensor2
'''

'\nsyntax\ntensor1.mul(tensor2)\ntensor1*tensor2\n'

In [33]:
t4 = ones_tensor*2
t4

tensor([[2., 4., 2.],
        [2., 4., 2.]])

In [34]:
t4.T

tensor([[2., 2.],
        [4., 4.],
        [2., 2.]])

In [35]:
ones_tensor*t4

tensor([[2., 8., 2.],
        [2., 8., 2.]])

In [36]:
#matrix multiplication
'''
syntax
tensor1.matmul(tensor1.T)

tensor @ tensor.T
'''
t3 = ones_tensor*t4
t4 @ t3.T

tensor([[40., 40.],
        [40., 40.]])

### In place operation

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.

!!!! Hence, their use is discouraged !!!!

In [37]:
t4

tensor([[2., 4., 2.],
        [2., 4., 2.]])

In [38]:
t4.add_(5)

tensor([[7., 9., 7.],
        [7., 9., 7.]])

## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

# Tensor to NumPy array

A change in the tensor reflects in the Numpy array bcoz Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [39]:
n_array = t4.numpy()

In [40]:
t4.add_(10)

tensor([[17., 19., 17.],
        [17., 19., 17.]])

In [41]:
n_array

array([[17., 19., 17.],
       [17., 19., 17.]], dtype=float32)

In [42]:
t_from_array = torch.from_numpy(np_array)

In [43]:
t_from_array

tensor([[2, 5],
        [6, 7]])

In [44]:
np.add(np_array,1,out=np_array)

array([[3, 6],
       [7, 8]])

In [45]:
t_from_array

tensor([[3, 6],
        [7, 8]])