# Tensors
- Similar to arrays & matrices
- In PyTorch uses tensors to encode :
    - inputs and outputs of a model 
    - model parameters
   
- Unlike Numpy ndarrays, tensors can run on GPUs & accelerated computing hardware

In [2]:
import torch
import numpy as np

# Tensor Initialization
1. Directly from data
2. From a Numpy array
3. From another tensor
4. With random or constant values

#### 1. Directly from data

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [8]:
type(data)

list

In [4]:
type(x_data)

torch.Tensor

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


### 2. From a NumPy array

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
type(x_np)

torch.Tensor

In [9]:
np_array.to(device) #can work if you use cupy but ... why?

AttributeError: 'numpy.ndarray' object has no attribute 'to'

In [10]:
x_np.to(device)

tensor([[1, 2],
        [3, 4]], device='cuda:0')

### 3. From another tensor:

- The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0298, 0.3741],
        [0.5565, 0.0538]]) 



### 4 . 

In [12]:
!nvidia-smi

Thu Sep 26 13:19:21 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P100-PCIE-16GB           Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P0             32W /  250W |     259MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----